services:
  streamlit:
    build: .
    volumes:
      - .:/app
    ports:
      - 8501:8501
    env_file:
    - .env
    command: "poetry run python -m streamlit run src/python_chat_ui/streamlit_main.py"
  gradio:
    build: .
    volumes:
      - .:/app
    ports:
      - 7860:7860
    env_file:
    - .env
    command: "poetry run gradio src/python_chat_ui/gradio_main.py"
  nicegui:
    build: .
    volumes:
      - .:/app
    ports:
      - 8080:8080
    env_file:
    - .env
    command: "poetry run python src/python_chat_ui/nicegui_main.py"
